blank_issues_enabled: false
contact_links:
  - name: Zoom Developer Forum
    url: https://devforum.zoom.us/c/rtms/99
    about: Please ask general questions about the Zoom APIs and SDKs here.
  - name: Zoom Developer Platform Documentation
    url: https://developers.zoom.us/docs/
    about: Check the official documentation for guides and API reference.
