name: Build and Deploy Documentation

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build docs
      run: docker compose run --rm docs-all
    - name: Setup docs
      run: |
        mkdir -p docs
        cp .github/docs-template/index.html docs/ || echo "No template"
    - uses: actions/configure-pages@v3
    - uses: actions/upload-pages-artifact@v2
      with:
        path: './docs'
    - uses: actions/deploy-pages@v2